---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~1.0
spec:
  releaseName: echo-prod
  chart:
    git: git@github.com:Aransh/echo.git
    path: charts/echo
    ref: master
  values:
    image:
      repository: gcr.io/echo-270609/echo
      tag: 1.0
    replicaCount: 3
