---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-stg
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:stg-*
spec:
  releaseName: echo-rc
  chart:
    git: git@github.com:Aransh/echo.git
    path: charts/echo
    ref: master
  values:
    image:
      repository: gcr.io/echo-270609/echo
      tag: stg-jxcjxc
    replicaCount: 2
    hpa:
      enabled: true
      maxReplicas: 10
      cpu: 50
      memory: 256Mi
